name: joy_bor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_gemini: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_tts: ^4.2.3
  font_awesome_flutter: ^10.6.0
  geolocator: ^14.0.2
  get: ^4.7.2
  google_maps_flutter: ^2.12.3
  http: ^1.4.0
  image_picker: ^1.1.2
  logger: ^2.6.1
  lottie: ^3.3.1
  permission_handler: ^12.0.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  speech_to_text: ^7.2.0
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
