// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQXghIRMTNCLvbXg7O_H3LCGEGJ19uNdE',
    appId: '1:136126691726:android:1257dc6639fda45e9bccdf',
    messagingSenderId: '136126691726',
    projectId: 'joy-bor-eb54f',
    storageBucket: 'joy-bor-eb54f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX96fCwguoD553tFkuKmdIKR95hSTIwhc',
    appId: '1:136126691726:ios:6d3ca1334c2c64d49bccdf',
    messagingSenderId: '136126691726',
    projectId: 'joy-bor-eb54f',
    storageBucket: 'joy-bor-eb54f.firebasestorage.app',
    androidClientId: '136126691726-kt9q20buhiqtekulelbf4ar6q79oj00t.apps.googleusercontent.com',
    iosClientId: '136126691726-s1o650c5b4fkv2iitrku67bq01iap6m0.apps.googleusercontent.com',
    iosBundleId: 'com.example.joyBor',
  );

}